homepage: "<your_project_homepage>"
language: c++
primary_contact: "<primary_contact_email>"
main_repo: "https://path/to/main/repo.git"
file_github_issue: true
sanitizers:
  - address
  - memory
     experimental: True
fuzzing_engines:
  - libfuzzer
  - afl
  - honggfuzz
